/**
 * emailService.js
 * Handles sending credentials and notifications via SMTP with development fallbacks
 */
const nodemailer = require('nodemailer');

class EmailService {
  constructor() {
    this.host = process.env.SMTP_HOST || '';
    this.port = parseInt(process.env.SMTP_PORT) || 587;
    this.user = process.env.SMTP_USER || '';
    this.password = process.env.SMTP_PASSWORD || '';
    this.from = process.env.SMTP_FROM || '"GIET Smart Bus Tracking" <noreply@giet.edu>';
    this.appUrl = process.env.APP_URL || 'http://localhost:5000';
  }

  isConfigured() {
    const host = process.env.SMTP_HOST || this.host;
    const user = process.env.SMTP_USER || this.user;
    const pass = process.env.SMTP_PASSWORD || this.password;
    return !!(host && user && pass);
  }

  getTransporter() {
    if (!this.isConfigured()) return null;
    const host = process.env.SMTP_HOST || this.host;
    const port = parseInt(process.env.SMTP_PORT) || this.port;
    const user = process.env.SMTP_USER || this.user;
    const pass = process.env.SMTP_PASSWORD || this.password;
    return nodemailer.createTransport({
      host,
      port,
      secure: port === 465,
      auth: {
        user,
        pass
      }
    });
  }

  /**
   * Sends account credentials to a new @giet.edu user
   */
  async sendAccountCredentials({ to, userId, tempPassword, role, name, simulateConfigured = false }) {
    if (simulateConfigured) {
      return { sent: true, reason: null, messageId: '<simulated-smtp@giet.edu>' };
    }
    const loginUrl = `${this.appUrl}/pages/${role}/login.html`;
    const roleCapitalized = role.charAt(0).toUpperCase() + role.slice(1);

    const emailSubject = 'GIET Smart Bus Tracking — Your Account';
    const emailBody = `
Dear ${name || 'User'},

Welcome to the GIET Smart University Bus Tracking System. An administrator has created your official account.

--------------------------------------------------
ACCOUNT CREDENTIALS
--------------------------------------------------
System User ID:      ${userId}
Registered Email:    ${to}
Assigned Role:       ${roleCapitalized}
Temporary Password:  ${tempPassword}
Login URL:           ${loginUrl}

--------------------------------------------------
IMPORTANT SECURITY INSTRUCTIONS:
--------------------------------------------------
1. This is a temporary password generated by the system.
2. You will be required to set a new, secure password immediately upon your first login.
3. Never share your credentials with anyone. GIET Transport administrators will never ask for your password.

If you have questions or suspect unauthorized access, contact the GIET Transport Office immediately.

Regards,
GIET University Transport Department
Gunupur, Odisha
    `.trim();

    const htmlBody = `
      <div style="font-family:Arial,sans-serif;max-width:580px;margin:0 auto;border:1px solid #e2e8f0;border-radius:12px;padding:24px;background:#ffffff;">
        <div style="text-align:center;padding-bottom:16px;border-bottom:2px solid #3b82f6;">
          <h2 style="color:#1e3a8a;margin:0;">🚌 GIET University</h2>
          <p style="color:#64748b;margin:4px 0 0;font-size:14px;">Smart Bus Tracking System</p>
        </div>
        <p style="color:#334155;margin-top:20px;">Dear <b>${name || 'User'}</b>,</p>
        <p style="color:#475569;line-height:1.5;">Your official account for the <b>GIET Smart Bus Tracking System</b> has been created by the transport administrator.</p>

        <div style="background:#f8fafc;border-left:4px solid #3b82f6;padding:16px;margin:20px 0;border-radius:4px;">
          <p style="margin:4px 0;color:#1e293b;"><b>System User ID:</b> <code style="background:#e2e8f0;padding:2px 6px;border-radius:4px;">${userId}</code></p>
          <p style="margin:4px 0;color:#1e293b;"><b>Registered Email:</b> ${to}</p>
          <p style="margin:4px 0;color:#1e293b;"><b>Role:</b> ${roleCapitalized}</p>
          <p style="margin:4px 0;color:#1e293b;"><b>Temporary Password:</b> <code style="background:#fee2e2;color:#b91c1c;padding:2px 6px;border-radius:4px;font-weight:bold;">${tempPassword}</code></p>
        </div>

        <div style="text-align:center;margin:24px 0;">
          <a href="${loginUrl}" style="background:#2563eb;color:#ffffff;padding:12px 24px;text-decoration:none;border-radius:8px;font-weight:bold;display:inline-block;">Login to Your Dashboard</a>
        </div>

        <div style="background:#fef2f2;border:1px solid #fecaca;border-radius:8px;padding:12px 16px;margin-top:20px;">
          <h4 style="color:#991b1b;margin:0 0 6px;">🔒 Security Notice:</h4>
          <p style="color:#7f1d1d;margin:0;font-size:13px;line-height:1.4;">
            This is a temporary password. You are <b>required to set a new password upon your first login</b>. Do not share your credentials with anyone.
          </p>
        </div>

        <hr style="border:none;border-top:1px solid #e2e8f0;margin:24px 0 16px;" />
        <p style="font-size:12px;color:#94a3b8;text-align:center;margin:0;">GIET University Transport Department • Gunupur, Odisha</p>
      </div>
    `;

    if (!this.isConfigured()) {
      // In development mode when SMTP is unconfigured: do not crash.
      // Return details safely so Admin UI can show them for dev inspection.
      const isProduction = process.env.NODE_ENV === 'production';
      return {
        sent: false,
        reason: 'SMTP is not configured in environment variables (SMTP_HOST, SMTP_USER, SMTP_PASSWORD).',
        devMode: !isProduction,
        devCredentials: isProduction ? undefined : {
          userId,
          system_user_id: userId,
          tempPassword,
          temporary_password: tempPassword,
          email: to,
          role
        }
      };
    }

    try {
      const transporter = this.getTransporter();
      await transporter.sendMail({
        from: this.from,
        to,
        subject: emailSubject,
        text: emailBody,
        html: htmlBody
      });
      return { sent: true, reason: null };
    } catch (err) {
      console.warn('⚠️  SMTP email delivery failed:', err.message);
      return {
        sent: false,
        reason: `Email delivery failed: ${err.message}`,
        devMode: process.env.NODE_ENV !== 'production',
        devCredentials: process.env.NODE_ENV !== 'production' ? {
          userId,
          system_user_id: userId,
          tempPassword,
          temporary_password: tempPassword,
          email: to,
          role
        } : null
      };
    }
  }
}

module.exports = new EmailService();
